test usuario

diff --git a/Documentos/jenkins/Jenkinsfile b/Documentos/jenkins/Jenkinsfile
--- a/Documentos/jenkins/Jenkinsfile
+++ b/Documentos/jenkins/Jenkinsfile
@@ -74,6 +74,9 @@ pipeline {
     	success {
             echo "-=- fin correcto -=-"
     	}
+    	failure {
+            echo "-=- fin ERROR -=-"
+    	}
         always {
         	script {
         	    sh "touch builds/build/rama/site/jacoco/unittest.zip"
@@ -83,6 +86,7 @@ pipeline {
 				attachLog: true, attachmentsPattern: 'builds/build/rama/site/jacoco/unittest.zip',
 				body: '${FILE,path="builds/build/rama/site/jacoco/index.html"}', 
 				subject: "Completado jenkins pipeline ${JOB_NAME} (${BUILD_NUMBER}) "
+    		sh "docker-compose down || true"
             echo "-=- fin -=-"
         }
     }
